export enum ProductEnum {
  GAZ_WALL_HEATING ='GAZ_WALL_HEATING',
  GAZ_FLOOR_HEATING ='GAZ_FLOOR_HEATING',
  OIL_FLOOR_HEATING ='OIL_FLOOR_HEATING',
  BOILER ='BOILER',
  PELLET_HEATER ='PELLET_HEATER',
  HEATER ='HEATER',
  INVALID =''
}



